my-news-site-api/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'news#index'
  resources :news, only: [:show, :index]

  namespace :admin do
    get '/', to: redirect('/admin/news')
    resources :news
  end
end

my-news-site-api/app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

my-news-site-api/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

my-news-site-api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

my-news-site-api/app/models/news.rb
class News < ApplicationRecord
  mount_uploader :image, ImageUploader

  after_initialize :set_defaults

  private
  def set_defaults
    self.hidden ||= false
  end
end

my-news-site-api/app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  def index
    @news = News.all
    render json: @news
  end

  def show
    render json: @news
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      render json: @news, status: :created
    else
      render json: @news.errors, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @news.update(news_params)
      render json: @news
    else
      render json: @news.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @news.destroy
    head :no_content
  end

  private

  def set_news
    @news = News.find(params[:id])
  end

  def news_params
    params.require(:news).permit(:title, :content, :published, :publish_date, :image)
  end
end

my-news-site-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

my-news-site-api/app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :update, :destroy]

  def index
    @news = if params[:start_date] && params[:end_date]
              date_range_filter
            else
              News.where(published: true, hidden: false)
            end
    render json: @news
  end

  def show
    render json: @news
  end

  def create
    @news = News.new(news_params)
    if @news.save
      render json: @news, status: :created, location: @news
    else
      render json: @news.errors, status: :unprocessable_entity
    end
  end

  def update
    if @news.update(news_params)
      render json: @news
    else
      render json: @news.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @news.destroy
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:title, :content, :published, :publish_date, :image)
    end

    def date_range_filter
      start_date = Date.parse(params[:start_date])
      end_date = Date.parse(params[:end_date])
      News.where("publish_date >= ? AND publish_date <= ?", start_date, end_date)
    end
end

my-news-site-api/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Админ-панель</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><%= link_to 'Список новостей', admin_news_index_path %></li>
        <li><%= link_to 'Создать новость', new_admin_news_path %></li>
      </ul>
    </nav>
  </header>

  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>
</body>
</html>

my-news-site-api/app/views/news/edit.html.erb
<h1>Редактирование новости</h1>

<%= form_with(model: @news, local: true) do |form| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "ошибка") %> запретили сохранение этой новости:</h2>
      <ul>
        <% @news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, 'Заголовок:' %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, 'Содержание:' %><br>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :published, 'Опубликовано:' %><br>
    <%= form.check_box :published %>
  </div>

  <div>
    <%= form.label :image, 'Изображение:' %><br>
    <%= form.file_field :image %><br>
    <% if @news.image? %>
      <p>Текущее изображение:</p>
      <%= image_tag @news.image.url %>
    <% end %>
  </div>

  <div>
    <%= form.submit "Сохранить новость" %>
  </div>
<% end %>

<%= link_to 'Вернуться к списку новостей', news_index_path %>

my-news-site-api/app/views/news/index.html.erb
<h1>Список новостей</h1>
<%= link_to 'Добавить новость', new_news_path %>
<table>
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Содержание</th>
      <th>Опубликовано</th>
      <th>Изображение</th>
      <th>Действия</th>
    </tr>
  </thead>
  <tbody>
    <% @news.each do |news_item| %>
      <tr>
        <td><%= news_item.title %></td>
        <td><%= news_item.content %></td>
        <td><%= news_item.published ? 'Да' : 'Нет' %></td>
        <td>
          <%= image_tag(news_item.image.url) if news_item.image? %>
        </td>
        <td>
          <%= link_to 'Редактировать', edit_news_path(news_item) %>
          <%= link_to 'Удалить', news_item, method: :delete, data: { confirm: 'Вы уверены?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

my-news-site-api/app/views/news/new.html.erb
<h1>Новая новость</h1>
<%= form_with(model: @news, local: true) do |form| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "ошибка") %> препятствует сохранению этой новости:</h2>
      <ul>
        <% @news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, "Заголовок:" %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, "Содержание:" %><br>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.label :published, "Опубликовано:" %><br>
    <%= form.check_box :published %>
  </div>
  <div>
    <%= form.label :publish_date, "Дата публикации:" %><br>
    <%= form.datetime_select :publish_date %>
  </div>
  <div>
    <%= form.label :image, "Изображение:" %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit "Сохранить" %>
  </div>
<% end %>